# Generated by Django 4.2.7 on 2023-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variety', models.TextField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('bud_type', models.CharField(max_length=50)),
                ('rose_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variety', models.TextField(max_length=100)),
                ('fruits', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
