# Generated by Django 4.2.7 on 2023-12-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variety', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='rose',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rose',
            name='price',
        ),
        migrations.RemoveField(
            model_name='rose',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rose',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='variety',
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('clients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.clients')),
                ('organisation', models.TextField(max_length=100)),
            ],
            bases=('main.clients',),
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('suppliersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('suppliersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsForSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
                ('purchaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sells')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsForPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
                ('purchaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchases')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.planttype'),
        ),
        migrations.AddField(
            model_name='rose',
            name='plantId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.plant'),
        ),
        migrations.AddField(
            model_name='tree',
            name='plantId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.plant'),
        ),
    ]
