# Generated by Django 4.2.7 on 2023-12-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clients_plant_planttype_status_users_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='PlantType',
            new_name='ProductType',
        ),
    ]
