# Generated by Django 4.2.7 on 2023-12-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_plant_products_rename_planttype_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsforpurchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsforpurchase',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productsforsell',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsforsell',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='amount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sells',
            name='amount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
