# Generated by Django 4.2.7 on 2023-12-24 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_suppliersid_sells_clientsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
