# Generated by Django 4.2.7 on 2023-12-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sells_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsforpurchase',
            name='amount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productsforsell',
            name='amount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
