# Generated by Django 4.2.7 on 2023-12-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productsforpurchase_amount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsforsell',
            name='amount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
