# Generated by Django 4.2.7 on 2023-12-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_productsforsell_amount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsforsell',
            old_name='purchaseId',
            new_name='sellId',
        ),
    ]
