# Generated by Django 4.2.7 on 2023-12-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sells_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
