# Generated by Django 4.2.7 on 2023-12-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_purchases_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='variety',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='organisation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
